// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'plugin_info.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `do_load_plugin`, `emit`, `get_available_plugins_internal`, `load_plugin_from_resolved_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StorageKey`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `hash`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `handle_plugin_request`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginManager>>
abstract class PluginManager implements RustOpaqueInterface {
  String get pluginsDir;

  set pluginsDir(String pluginsDir);

  Future<List<PluginInfo>> getAvailablePlugins();

  /// FIX M-02: No longer uses block_on — uses std::sync::RwLock directly.
  Future<List<String>> getLoadedPlugins();

  Stream<PluginManagerEvent> initEventStream();

  /// FIX M-02: is_plugin_loaded is now a fully async function that only
  /// acquires the std RwLock for the map lookup, then the tokio Mutex for
  /// type verification. No block_on involved.
  Future<bool> isPluginLoaded(
      {required String pluginId, required PluginType pluginType});

  Future<bool> isPluginLoadedById(
      {required String pluginId, required PluginType pluginType});

  Future<void> loadPlugin({required PluginInfo pluginInfo});

  Future<void> loadPluginById(
      {required String pluginId, required PluginType pluginType});

  Future<void> loadPluginFromPath(
      {required String pluginId,
      required PluginType pluginType,
      required String pluginPath});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PluginManager> newInstance({required String pluginsDir}) =>
      RustLib.instance.api
          .crateApiPluginPluginPluginManagerNew(pluginsDir: pluginsDir);

  Future<void> refreshAvailablePlugins();

  Future<void> shutdown();

  Future<void> storageClear({required String pluginId});

  Future<bool> storageDelete({required String pluginId, required String key});

  Future<String?> storageGet({required String pluginId, required String key});

  Future<void> storagePreload(
      {required String pluginId, required String key, required String value});

  Future<bool> storageSet(
      {required String pluginId, required String key, required String value});

  Future<void> unloadPlugin(
      {required String pluginId, required PluginType pluginType});

  Future<void> unloadPluginById(
      {required String pluginId, required PluginType pluginType});
}
